# Master 2024 EDA notebook

# 0. Config

In [64]:
from matplotlib import pyplot as plt
import pandas as pd
from datetime import datetime

In [65]:
pd.set_option("display.max_columns", None)

# 1. Data

In [66]:
path = "../../data/MASTER_2024.csv"
df_master_stats = pd.read_csv(path)

# 2. Analysis

In [67]:
df_master_stats.head()

,N-NUMBER,SERIAL NUMBER,MFR MDL CODE,ENG MFR MDL,YEAR MFR,TYPE REGISTRANT,NAME,STREET,STREET2,CITY,STATE,ZIP CODE,REGION,COUNTY,COUNTRY,LAST ACTION DATE,CERT ISSUE DATE,CERTIFICATION,TYPE AIRCRAFT,TYPE ENGINE,STATUS CODE,MODE S CODE,FRACT OWNER,AIR WORTH DATE,OTHER NAMES(1),OTHER NAMES(2),OTHER NAMES(3),OTHER NAMES(4),OTHER NAMES(5),EXPIRATION DATE,UNIQUE ID,KIT MFR,KIT MODEL,MODE S CODE HEX
0,100,5334,7100510,17003.0,1940.0,1,BENE MARY D,PO BOX 329,NaN,KETCHUM,OK,743490329,2,97.0,US,20230122,20050506.0,1,4,1,V,50002263,,19540430.0,NaN,NaN,NaN,NaN,NaN,20270430.0,600060,NaN,NaN,A004B3
1,10000,10000,2130004,NaN,NaN,7,9AT LLC,511 WEDGEWOOD AVE,NaN,NASHVILLE,TN,372035521,3,37.0,US,20240823,20240823.0,NaN,4,1,V,50003445,,NaN,NaN,NaN,NaN,NaN,NaN,20310831.0,1443200,NaN,NaN,A00725
2,10001,A28,9601202,67007.0,1928.0,1,STOOS ROBERT A,PO BOX 1056,NaN,LAKELAND,FL,338021056,7,105.0,US,20230718,20190227.0,1,4,1,V,50003446,,NaN,NaN,NaN,NaN,NaN,NaN,20290228.0,432072,NaN,NaN,A00726
3,10004,T18208245,2072738,NaN,NaN,7,ETOS AIR LLC,PO BOX 288,NaN,NEW LONDON,TX,756820288,2,401.0,US,20230722,20130312.0,NaN,4,2,V,50003451,,NaN,NaN,NaN,NaN,NaN,NaN,20290331.0,102879,NaN,NaN,A00729
4,10006,BG-72,1152020,17026.0,1955.0,1,COUTCHES ROBERT HERCULES DBA,550 AIRWAY BLVD,NaN,LIVERMORE,CA,945519533,4,1.0,US,20230421,19980826.0,1U,4,1,V,50003453,,19710909.0,AERO FLIGHT AVIATION,NaN,NaN,NaN,NaN,20280229.0,480110,NaN,NaN,A0072B

In [68]:
df_master_stats.describe()

,ENG MFR MDL,YEAR MFR,COUNTY,LAST ACTION DATE,CERT ISSUE DATE,TYPE ENGINE,MODE S CODE,AIR WORTH DATE,EXPIRATION DATE,UNIQUE ID
count,271894.000000,242985.000000,297855.000000,2.997950e+05,2.943040e+05,299795.000000,2.997950e+05,2.674780e+05,2.942540e+05,2.997950e+05
mean,34356.769417,1982.387958,89.857726,2.023163e+07,2.015803e+07,2.244984,5.155867e+07,1.988096e+07,2.028918e+07,6.407695e+05
std,18982.782249,54.937981,106.661735,1.599835e+04,9.552916e+04,2.461988,1.024083e+06,2.182482e+05,1.262704e+04,4.231308e+05
min,0.000000,0.000000,0.000000,1.971112e+07,1.940123e+07,0.000000,5.000000e+07,1.920121e+07,2.018023e+07,0.000000e+00
25%,17026.000000,1966.000000,25.000000,2.023043e+07,2.013012e+07,1.000000,5.060158e+07,1.969033e+07,2.028043e+07,2.736830e+05
50%,41508.000000,1979.000000,61.000000,2.023072e+07,2.019083e+07,1.000000,5.147377e+07,1.984011e+07,2.029043e+07,5.905960e+05
75%,41597.000000,2005.000000,113.000000,2.023093e+07,2.023012e+07,2.000000,5.243439e+07,2.008011e+07,2.030033e+07,9.653215e+05
max,99999.000000,2024.000000,999.000000,2.024123e+07,2.024123e+07,11.000000,5.337370e+07,2.024123e+07,2.031123e+07,1.484132e+06

In [69]:
list_cols_check = [
  'N-NUMBER',
  'YEAR MFR',
  'LAST ACTION DATE',
  'CERT ISSUE DATE',
  'AIR WORTH DATE',
  'EXPIRATION DATE'

]

In [70]:
df_master_stats.columns

Index(['N-NUMBER', 'SERIAL NUMBER', 'MFR MDL CODE', 'ENG MFR MDL', 'YEAR MFR',
       'TYPE REGISTRANT', 'NAME', 'STREET', 'STREET2', 'CITY', 'STATE',
       'ZIP CODE', 'REGION', 'COUNTY', 'COUNTRY', 'LAST ACTION DATE',
       'CERT ISSUE DATE', 'CERTIFICATION', 'TYPE AIRCRAFT', 'TYPE ENGINE',
       'STATUS CODE', 'MODE S CODE', 'FRACT OWNER', 'AIR WORTH DATE',
       'OTHER NAMES(1)', 'OTHER NAMES(2)', 'OTHER NAMES(3)', 'OTHER NAMES(4)',
       'OTHER NAMES(5)', 'EXPIRATION DATE', 'UNIQUE ID', 'KIT MFR',
       ' KIT MODEL', 'MODE S CODE HEX'],
      dtype='object')

In [71]:
df_master_stats[list_cols_check].nunique().sort_values()

EXPIRATION DATE        105
YEAR MFR               114
LAST ACTION DATE      1526
CERT ISSUE DATE      13114
AIR WORTH DATE       23572
N-NUMBER            299795
dtype: int64

In [ ]:
#for col in list_cols_check:
#
#    print(col)
#    df_master_stats[col].hist()
#    plt.show()

# 3. Processing

In [90]:
df_master_stats_proc = df_master_stats.copy()
df_master_stats_proc = df_master_stats_proc.reset_index()

#Rename N Number to Tail number
df_master_stats_proc.rename(columns={'N-NUMBER': 'TailNumber'}, inplace=True)

In [91]:

list_cols = [    
  'TailNumber',
  'YEAR MFR',
  'LAST ACTION DATE',
  'CERT ISSUE DATE',
  'AIR WORTH DATE',
  'EXPIRATION DATE'
]

In [92]:
df_master_stats_proc= df_master_stats_proc.loc[:, list_cols]

In [93]:
#Data conversion.
#TODO: Keeping na as such. Do we need to exclude those records or change it to default date?
#YEAR MFR is still in float due to na values. Once default is assigned then it will becomes int.

# Convert 'CERT ISSUE DATE' from float to datetime format (YYYYMMDD). 
df_master_stats_proc['CERT ISSUE DATE'] = df_master_stats_proc['CERT ISSUE DATE'].fillna(0).apply(lambda x: datetime.strptime(str(int(x)), '%Y%m%d') if x != 0 else None)

# Convert 'AIR WORTH DATE' from float to datetime format (YYYYMMDD).
df_master_stats_proc['AIR WORTH DATE'] = df_master_stats_proc['AIR WORTH DATE'].fillna(0).apply(lambda x: datetime.strptime(str(int(x)), '%Y%m%d') if x != 0 else None)

# Convert 'EXPIRATION DATE' from float to datetime format (YYYYMMDD).
df_master_stats_proc['EXPIRATION DATE'] = df_master_stats_proc['EXPIRATION DATE'].fillna(0).apply(lambda x: datetime.strptime(str(int(x)), '%Y%m%d') if x != 0 else None)

# Convert 'LAST ACTION DATE' from float to datetime format (YYYYMMDD).
df_master_stats_proc['LAST ACTION DATE'] = df_master_stats_proc['LAST ACTION DATE'].fillna(0).apply(lambda x: datetime.strptime(str(int(x)), '%Y%m%d') if x != 0 else None)

# Convert 'YEAR MFR' from float to integer.
df_master_stats_proc['YEAR MFR'] = df_master_stats_proc['YEAR MFR'].apply(lambda x: int(x) if pd.notna(x) else None)

In [94]:
# Calculate NaN statistics
total_records = len(df_master_stats_proc)
nan_count = df_master_stats_proc.isna().sum()
nan_percentage = (nan_count / total_records) * 100

# Display results
nan_stats = pd.DataFrame({'NaN Count': nan_count, 'Total Records': total_records, 'NaN Percentage (%)': nan_percentage}).round(2)
print(nan_stats)

                  NaN Count  Total Records  NaN Percentage (%)
TailNumber                0         299795                0.00
YEAR MFR              56810         299795               18.95
LAST ACTION DATE          0         299795                0.00
CERT ISSUE DATE        5491         299795                1.83
AIR WORTH DATE        32317         299795               10.78
EXPIRATION DATE        5541         299795                1.85

In [95]:
#Derived columns
current_year = datetime.now().year
current_date = datetime.now()

# Calculate age and create a new column 'Age_Year_Mfr'
df_master_stats_proc['Age_Year_Mfr'] = df_master_stats_proc['YEAR MFR'].apply(lambda x: current_year - x if pd.notna(x) else None)

# Calculate age in days for last action, cert issue and Air worth dates
df_master_stats_proc['AgeDays_Last_Action_Date'] = df_master_stats_proc['LAST ACTION DATE'].apply(lambda x: (current_date - x).days if pd.notna(x) else None)
df_master_stats_proc['AgeDays_Cert_Issue_Date'] = df_master_stats_proc['CERT ISSUE DATE'].apply(lambda x: (current_date - x).days if pd.notna(x) else None)
df_master_stats_proc['AgeDays_Air_Worth_Date'] = df_master_stats_proc['AIR WORTH DATE'].apply(lambda x: (current_date - x).days if pd.notna(x) else None)

# Calculate days until EXPIRATION DATE
df_master_stats_proc['Days_Until_Expiration_Date'] = df_master_stats_proc['EXPIRATION DATE'].apply( lambda x: (x - current_date).days if pd.notna(x) else None)

In [96]:
df_master_stats_proc

,TailNumber,YEAR MFR,LAST ACTION DATE,CERT ISSUE DATE,AIR WORTH DATE,EXPIRATION DATE,Age_Year_Mfr,AgeDays_Last_Action_Date,AgeDays_Cert_Issue_Date,AgeDays_Air_Worth_Date,Days_Until_Expiration_Date
0,100,1940.0,2023-01-22,2005-05-06,1954-04-30,2027-04-30,85.0,785,7255.0,25889.0,773.0
1,10000,NaN,2024-08-23,2024-08-23,NaT,2031-08-31,NaN,206,206.0,NaN,2357.0
2,10001,1928.0,2023-07-18,2019-02-27,NaT,2029-02-28,97.0,608,2210.0,NaN,1443.0
3,10004,NaN,2023-07-22,2013-03-12,NaT,2029-03-31,NaN,604,4388.0,NaN,1474.0
4,10006,1955.0,2023-04-21,1998-08-26,1971-09-09,2028-02-29,70.0,696,9700.0,19548.0,1078.0
...,...,...,...,...,...,...,...,...,...,...,...
299790,9ZR,NaN,2023-08-16,2023-08-16,1993-10-21,2030-08-31,NaN,579,579.0,11470.0,1992.0
299791,9ZS,1974.0,2023-06-03,1996-09-23,1976-03-12,2028-08-31,51.0,653,10402.0,17902.0,1262.0
299792,9ZT,2001.0,2024-09-10,2022-05-09,2001-09-06,2029-05-31,24.0,188,1043.0,8593.0,1535.0
299793,9ZU,1959.0,2023-04-01,2017-11-14,2001-10-10,2027-11-30,66.0,716,2680.0,8559.0,987.0
299794,9ZX,1986.0,2023-03-10,2023-03-10,1986-07-31,2030-03-31,39.0,738,738.0,14109.0,1839.0

In [97]:
df_master_stats_proc

,TailNumber,YEAR MFR,LAST ACTION DATE,CERT ISSUE DATE,AIR WORTH DATE,EXPIRATION DATE,Age_Year_Mfr,AgeDays_Last_Action_Date,AgeDays_Cert_Issue_Date,AgeDays_Air_Worth_Date,Days_Until_Expiration_Date
0,100,1940.0,2023-01-22,2005-05-06,1954-04-30,2027-04-30,85.0,785,7255.0,25889.0,773.0
1,10000,NaN,2024-08-23,2024-08-23,NaT,2031-08-31,NaN,206,206.0,NaN,2357.0
2,10001,1928.0,2023-07-18,2019-02-27,NaT,2029-02-28,97.0,608,2210.0,NaN,1443.0
3,10004,NaN,2023-07-22,2013-03-12,NaT,2029-03-31,NaN,604,4388.0,NaN,1474.0
4,10006,1955.0,2023-04-21,1998-08-26,1971-09-09,2028-02-29,70.0,696,9700.0,19548.0,1078.0
...,...,...,...,...,...,...,...,...,...,...,...
299790,9ZR,NaN,2023-08-16,2023-08-16,1993-10-21,2030-08-31,NaN,579,579.0,11470.0,1992.0
299791,9ZS,1974.0,2023-06-03,1996-09-23,1976-03-12,2028-08-31,51.0,653,10402.0,17902.0,1262.0
299792,9ZT,2001.0,2024-09-10,2022-05-09,2001-09-06,2029-05-31,24.0,188,1043.0,8593.0,1535.0
299793,9ZU,1959.0,2023-04-01,2017-11-14,2001-10-10,2027-11-30,66.0,716,2680.0,8559.0,987.0
299794,9ZX,1986.0,2023-03-10,2023-03-10,1986-07-31,2030-03-31,39.0,738,738.0,14109.0,1839.0

# 4. Export

In [98]:
path = "../../outputs/raw/"

In [100]:
df_dd = df_master_stats.dtypes.to_frame().reset_index()
df_dd.columns = ["column", "dtype"]
df_dd.to_csv(f"{path}MasterData_dictionary.csv", index=False)

In [101]:
path = "../../outputs/proc/"

In [102]:
df_dd = df_master_stats_proc.dtypes.to_frame().reset_index()
df_dd.columns = ["column", "dtype"]
df_dd.to_csv(f"{path}MasterData_dictionary.csv", index=False)

In [ ]:
df_master_stats_proc.to_csv(f"{path}FlightMasterData.csv", index=False)